### ISSUE TITLE
Edit time slot with drag and drop

### ISSUE THREAD

**Issue by mrozbarry** [FRFlor/social-mob#3]
Instead of opening the edit dialog, allow the owner of a mob to drag their mob card to different days/time slots.

**Comment by FRFlor** [comment]
Done! Now the owner can move their mobs to different days by drag and dropping.

A mob is editable if it's in the current day or the future. I'm preventing edits to mobs in the past because I'm hoping we'll have a history of all the social mobs we have. 

For mobs in the past, I'll make it so that you can make a clone of it in the day that you drag it to, but that feature is not yet done.

**Comment by FRFlor** [comment]
![drag-drop](https://user-images.githubusercontent.com/22578748/82773548-502ccc80-9e10-11ea-96a7-90e833173aae.gif)

**Comment by mrozbarry** [comment]
I wouldn't mind if when dragging, you could also drag up and down to update the hour (or whatever time slot) to change the time, too. That might be a different issue, though.

**Comment by FRFlor** [comment]
Even though the mobs are sorted vertically by start_time, the day  column doesn't have timeslot rows per say, since multiple mobs can be happening at the same time (different locations). To allow changing start_time by drag-drop I would have to put empty hour-slots on the days to receive the cards, which could move attention away from existing cards.

**Comment by FRFlor** [comment]
Mmmm... What if...

As soon as you start dragging a card, 4 dropzones appear in the day that card came from.

- Advance by 1 hour
- Advance by 30 min
< Card that was dragged was here>
- Postpone by 30 min
- Postpone by 1 hour

Then the user can drop the card in one of those 4 dropzones to change the start_time accordingly

The hour change dropzone then disappear. So it wouldn't be cluttering the ui too much.

**Comment by mrozbarry** [comment]
Hmmm. I think we might want to park this idea for the time being, now that I've thought about it. Maybe see if anyone else thumbs this issue, at least, I think I might be the minority when it comes to this feature. Like, it sounds neat, but I'm not sure if it's actually practical...not unless each column was more like a full day, and I'm not sure that's the right move.
